/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.cloudws.swing;

import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import org.iesapp.cloudws.client.CloudClientSession;
import org.iesapp.cloudws.client.FileInfo;

/**
 *
 * @author Josep
 */
public class CloudBrowserDlg extends javar.JRDialog {

    protected int option = 0;
    public static final int ACCEPT_OPTION = 1;
    public static final int CANCEL_OPTION = 0;
    
    /**
     * Creates new form CloudBrowserDlg
     */
    public CloudBrowserDlg(java.awt.Frame parent, boolean modal) {
        super(parent, true);
        initComponents();
        this.setTitle("Cloud Browser - Offline");
        this.setIconImage(new ImageIcon(CloudBrowserDlg.class.getResource("/org/iesapp/cloudws/icons/cloud.png")).getImage());
    }
    
    public void setSession(CloudClientSession session)
    {
        this.cloudBrowserPanel2.setSession(session);
        this.setTitle("Cloud Browser"+File.separator+session.getHome());
    }

    public ArrayList<FileInfo> getSelectedFiles() {
        return this.cloudBrowserPanel2.getSelectedFiles();
    }
    
    public FileInfo getSelectedFile() {
        return this.cloudBrowserPanel2.getSelectedFile();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cloudBrowserPanel2 = new org.iesapp.cloudws.swing.CloudBrowserPanel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/iesapp/cloudws/bundle"); // NOI18N
        jButton1.setText(bundle.getString("choose")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(bundle.getString("cancel")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cloudBrowserPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(cloudBrowserPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        option = ACCEPT_OPTION;
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CloudBrowserDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CloudBrowserDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CloudBrowserDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CloudBrowserDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                CloudBrowserDlg dialog = new CloudBrowserDlg(new javax.swing.JFrame(), true);
              
                CloudClientSession.baseURL = "http://localhost:8080/pdaweb/webresources/cloud/";
                CloudClientSession session = new CloudClientSession("sforlano","7080");
                dialog.setSession(session);
                dialog.setVisible(true);
                
                if(dialog.option==CloudBrowserDlg.ACCEPT_OPTION)
                {
                //System.out.println(dialog.getSelectedFile().getUrl());
                //System.out.println(dialog.getOption());
                }
                dialog.dispose();
                
                System.exit(0);
            }
        });
    }
    
    public int getOption()
    {
        return option;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.iesapp.cloudws.swing.CloudBrowserPanel cloudBrowserPanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
