/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.modules.cloud;

import javax.swing.SwingUtilities;
import org.iesapp.cloudws.client.CloudClientSession;
import org.iesapp.cloudws.swing.CloudBrowserPanel;
import org.iesapp.framework.pluggable.TopModuleWindow;
import org.iesapp.framework.util.CoreCfg;

/**
 *
 * @author Josep
 */
public class CloudModule extends TopModuleWindow {

    CloudClientSession session;
    String lastUser = null;
    private final CloudBrowserPanel cloudBrowserPanel1;
    
    public CloudModule()
    {
           initComponents();      
           CloudClientSession.baseURL = CoreCfg.cloudBaseURL;
           cloudBrowserPanel1 = new CloudBrowserPanel();
           this.add(cloudBrowserPanel1);
    }   
 
    
    @Override
    public void refreshUI() {
        
       SwingUtilities.invokeLater(new CreateSession());
    }
    
    @Override
    public void dispose() {
        super.dispose();
        if(session!=null)
        {
            session.close();
            session = null;
            cloudBrowserPanel1.setSession(session);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    private class CreateSession implements Runnable
    {
       @Override
        public void run() {
            String systemUser = coreCfg.getUserInfo().getSystemUser();
            if (systemUser != null && (lastUser == null || lastUser.equals(systemUser))) {
                if (session != null) {
                    session.close();
                }
                session = new CloudClientSession(coreCfg.getUserInfo().getSystemUser(), coreCfg.getUserInfo().getClaveUP());
                cloudBrowserPanel1.setSession(session);

            }
        }
    }

}
